# Generated by Django 3.2 on 2022-06-17 08:42

import backend.banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='no_image_available.png', null=True, upload_to=backend.banner.models.user_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'db_table': 'banner',
            },
        ),
    ]
