# Generated by Django 4.0.5 on 2022-09-12 10:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
