# Generated by Django 4.0.5 on 2022-09-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webp_converter', '0003_auto_20191202_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
