# Generated by Django 3.2 on 2023-04-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='sheculed_classes',
            new_name='schedule_classes',
        ),
    ]
