# Generated by Django 3.2 on 2023-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_rename_sheculed_classes_timetable_schedule_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='is_accepted',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='0', max_length=20),
        ),
    ]
