# Generated by Django 4.0.5 on 2023-04-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_classes_timetable_classes_and_more'),
        ('timetable', '0003_auto_20230414_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='period',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='schedule_date',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='schedule_classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes_timetable_period'),
        ),
    ]
