# Generated by Django 3.2 on 2023-04-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_timetable_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_moved',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=20, null=True),
        ),
    ]
