# Generated by Django 4.0.5 on 2023-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('teacher', '0003_teacher_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phoneNo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='subject.subject'),
        ),
    ]
