# Generated by Django 3.2 on 2023-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_std_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=20, null=True),
        ),
    ]
