# Generated by Django 4.0.5 on 2023-04-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classes_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes_timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THUR', 'THUR'), ('FRI', 'FRI')], default='Y', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classes')),
            ],
            options={
                'verbose_name': 'classes_timetable',
                'verbose_name_plural': 'classes_timetable',
                'db_table': 'classes_timetable',
            },
        ),
        migrations.CreateModel(
            name='classes_timetable_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='Y', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classes')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classes_timetable')),
            ],
            options={
                'verbose_name': 'classes_timetable_period',
                'verbose_name_plural': 'classes_timetable_period',
                'db_table': 'classes_timetable_period',
            },
        ),
    ]
