# Generated by Django 4.0.5 on 2023-04-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classes_timetable_classes_timetable_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_timetable',
            name='day',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
