# Generated by Django 4.0.5 on 2023-04-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('classes', '0005_alter_classes_timetable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes_timetable_period',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.subject'),
        ),
    ]
