# Generated by Django 3.2 on 2023-04-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classes_timetable_period_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_timetable_period',
            name='day',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classes_timetable_period',
            name='period',
            field=models.IntegerField(default=1),
        ),
    ]
