# Generated by Django 4.0.5 on 2023-04-17 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('classes', '0007_auto_20230417_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_timetable',
            name='classes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='classes_timetable_period',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='classes_timetable_period',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
