# Generated by Django 3.2 on 2022-05-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMS_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0, null=True)),
                ('page_title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_header', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=20, null=True)),
                ('is_footer', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=20, null=True)),
                ('is_active', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmspage.cms_page')),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
            },
        ),
    ]
