# Generated by Django 3.2 on 2022-05-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cms_page',
            table='cms_page',
        ),
    ]
