# Generated by Django 3.2 on 2022-06-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmspage', '0002_alter_cms_page_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_page',
            name='is_active',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cms_page',
            name='parent_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'level_id': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmspage.cms_page'),
        ),
    ]
