# Generated by Django 3.2 on 2022-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspage', '0003_auto_20220617_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_page',
            name='meta_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cms_page',
            name='meta_keyword',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cms_page',
            name='meta_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
