# Generated by Django 4.0.5 on 2022-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspage', '0004_auto_20220712_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_page',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
