# Generated by Django 4.0.5 on 2022-09-12 10:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmspage', '0005_cms_page_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_page',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cms_page',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
